formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
linters:
  default: standard
  enable:
    - exhaustive
    - exhaustruct
    - gochecknoglobals
    - gochecknoinits
    - nonamedreturns
    - paralleltest
    - predeclared
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
  settings:
    paralleltest:
      ignore-missing-subtests: true
version: '2'
