jobs:
  setup:
    name: CI
    runs-on: ubuntu-latest
    steps:
      # https://github.com/marketplace/actions/checkout
      - name: Checkout Repo
        uses: actions/checkout@v4
      # https://github.com/marketplace/actions/setup-go-environment
      - name: Set up Go 1.x >= 1.18
        uses: actions/setup-go@v5
        with:
          # requires go.sum file (i.e., external libraries)
          go-version-file: go.mod
      # https://github.com/marketplace/actions/golangci-lint#how-to-use
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v7
        with:
          version: latest
      - name: go test
        run: go test -v ./...
      - name: Install yamllint
        run: pip install yamllint
      - name: Lint YAML files
        run: yamllint .
name: CI
on: # yamllint disable-line rule:truthy
  pull_request:
  push:
    branches:
      - master
  workflow_call:
permissions:
  contents: read
