jobs:
  ci:
    uses: ./.github/workflows/ci.yml
  setup:
    name: Release
    needs: ci
    runs-on: ubuntu-latest
    steps:
      # https://github.com/marketplace/actions/checkout`
      - name: Checkout Repo
        uses: actions/checkout@v3
      # https://github.com/marketplace/actions/setup-go-environment
      - name: Set up Go 1.x >= 1.18
        uses: actions/setup-go@v3
        with:
          # requires go.sum file (i.e., external libraries)
          cache: true
          go-version-file: go.mod
      # https://github.com/marketplace/actions/goreleaser-action
      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          KEY_GITHUB_GORELEASER_TO_HOMEBREW_TAP: ${{ secrets.KEY_GITHUB_GORELEASER_TO_HOMEBREW_TAP }}
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v3
        with:
          args: release --rm-dist
          version: latest
name: Release
on: # yamllint disable-line rule:truthy
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
permissions:
  contents: write
